## @file
## @ros_srv Service for simple addition.
##
## This service does something.

## @name Request
##@{

int64 a ##< Input data
int64 b ##< Input data

##@}
---
## @name Response
##@{

int64 sum ##< Result of addition

##@}
