## @file 
## @ros_srv Purpose of this ROS Service.
##
## This service does something.

## @name Request
##@{

uint32 input_data  ##< Request data

##@}
---
## @name Response
##@{

uint32 return_data ##< Response data

##@}
